long:
	g++ -o draw polygon.cpp Lines.cpp DigitalDifferentialAnalyzer.cpp Bresenham.cpp Draw.cpp Comm.cpp main.cpp -framework GLUT -framework OpenGL -lcurses -Wno-deprecated -Wc++11-extensions

clean:
	rm *.o

cleanall:
	rm *.o draw
